# Generated by Django 4.1.2 on 2022-10-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='Job_Advert',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='Job_applicatin', to='myapp.jobadvert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='upload_cv',
            field=models.FileField(null=True, upload_to='static/myapp'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='years_of_experience',
            field=models.CharField(choices=[('0 - 1', '0 - 1'), ('1 - 2', '1 - 2'), ('3 - 4', '3 - 4'), ('5 - 6', '5 - 6'), ('7 and above', '7 and above')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
