# Generated by Django 4.1.2 on 2022-10-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobapplication_job_advert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvert',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='time_and_date_applied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Job_Advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_application', to='myapp.jobadvert'),
        ),
    ]
